4.7,   price_change_7d:12.3, market_cap:95000000000,   total_volume:4200000000,  circulating_supply:'470M' },
  { rank:6,  coin_id:'xrp',       symbol:'XRP', name:'XRP',           current_price:0.617,  price_change_24h_pct:-1.2,  price_change_7d:-2.1, market_cap:34000000000,   total_volume:1100000000,  circulating_supply:'55B'  },
    { rank:7,  coin_id:'usdc',      symbol:'USDC',name:'USD Coin',      current_price:1.0,    price_change_24h_pct:0.02,  price_change_7d:0.0,  market_cap:44000000000,   total_volume:7800000000,  circulating_supply:'44B'  },
      { rank:8,  coin_id:'avalanche', symbol:'AVAX',name:'Avalanche',     current_price:38.9,   price_change_24h_pct:-1.2,  price_change_7d:2.8,  market_cap:15700000000,   total_volume:620000000,   circulating_supply:'403M' },
        { rank:9,  coin_id:'chainlink', symbol:'LINK',name:'Chainlink',     current_price:18.4,   price_change_24h_pct:5.2,   price_change_7d:9.1,  market_cap:11200000000,   total_volume:880000000,   circulating_supply:'608M' },
          { rank:10, coin_id:'polkadot',  symbol:'DOT', name:'Polkadot',      current_price:8.21,   price_change_24h_pct:-0.8,  price_change_7d:-3.2, market_cap:12400000000,   total_volume:430000000,   circulating_supply:'1.5B' },
          ];
          
          const fmt = v => v >= 1e12 ? `$${(v/1e12).toFixed(2)}T` : v >= 1e9 ? `$${(v/1e9).toFixed(1)}B` : `$${(v/1e6).toFixed(0)}M`;
          
          export default function Markets() {
            const [sortKey, setSortKey] = useState('rank');
              const [sortDir, setSortDir] = useState('asc');
                const [filter, setFilter] = useState('');
                
                  const sorted = [...COINS]
                      .filter(c => c.name.toLowerCase().includes(filter.toLowerCase()) || c.symbol.toLowerCase().includes(filter.toLowerCase()))
                          .sort((a,b) => sortDir === 'asc' ? (a[sortKey] > b[sortKey] ? 1 : -1) : (a[sortKey] < b[sortKey] ? 1 : -1));
                          
                            const toggleSort = key => { if (sortKey === key) setSortDir(d => d === 'asc' ? 'desc' : 'asc'); else { setSortKey(key); setSortDir('asc'); } };
                            
                              const Th = ({ label, k }) => (
                                  <th onClick={() => toggleSort(k)} className="text-left px-4 py-3 text-xs text-gray-500 font-medium uppercase tracking-wider cursor-pointer hover:text-gray-300 select-none">
                                        <span className="flex items-center gap-1">{label}<ArrowUpDown size={10}/></span>
                                            </th>
                                              );
                                              
                                                const Pct = ({ v }) => <span className={`text-sm font-medium flex items-center gap-1 ${ v >= 0 ? 'text-emerald-400' : 'text-red-400' }`}>
                                                    {v >= 0 ? <TrendingUp size={12}/> : <TrendingDown size={12}/>}{v >= 0 ? '+' : ''}{v.toFixed(2)}%
                                                      </span>;
                                                      
                                                        return (
                                                            <div className="p-6">
                                                                  <div className="flex items-center justify-between mb-6">
                                                                          <h1 className="text-xl font-bold text-white">Markets</h1>
                                                                                  <input value={filter} onChange={e=>setFilter(e.target.value)} placeholder="Filter coins..." className="bg-[#0d1424] border border-gray-700 rounded-lg px-4 py-2 text-sm text-white placeholder-gray-500 outline-none w-56" />
                                                                                        </div>
                                                                                              <div className="bg-[#0d1424] rounded-xl border border-gray-800 overflow-hidden">
                                                                                                      <table className="w-full text-sm">
                                                                                                                <thead className="border-b border-gray-800">
                                                                                                                            <tr>
                                                                                                                                          <Th label="#" k="rank" />
                                                                                                                                                        <Th label="Name" k="name" />
                                                                                                                                                                      <Th label="Price" k="current_price" />
                                                                                                                                                                                    <Th label="24h" k="price_change_24h_pct" />
                                                                                                                                                                                                  <Th label="7d" k="price_change_7d" />
                                                                                                                                                                                                                <Th label="Market Cap" k="market_cap" />
                                                                                                                                                                                                                              <Th label="Volume 24h" k="total_volume" />
                                                                                                                                                                                                                                            <th className="text-left px-4 py-3 text-xs text-gray-500 font-medium uppercase tracking-wider">Supply</th>
                                                                                                                                                                                                                                                        </tr>
                                                                                                                                                                                                                                                                  </thead>
                                                                                                                                                                                                                                                                            <tbody>
                                                                                                                                                                                                                                                                                        {sorted.map(c => (
                                                                                                                                                                                                                                                                                                      <tr key={c.coin_id} className="border-b border-gray-800/40 hover:bg-gray-800/20 transition-colors cursor-pointer">
                                                                                                                                                                                                                                                                                                                      <td className="px-4 py-3 text-gray-500">{c.rank}</td>
                                                                                                                                                                                                                                                                                                                                      <td className="px-4 py-3">
                                                                                                                                                                                                                                                                                                                                                        <div className="flex items-center gap-3">
                                                                                                                                                                                                                                                                                                                                                                            <div className="w-7 h-7 rounded-full bg-gray-700 flex items-center justify-center text-xs font-bold text-white">{c.symbol.slice(0,2)}</div>
                                                                                                                                                                                                                                                                                                                                                                                                <div>
                                                                                                                                                                                                                                                                                                                                                                                                                      <p className="text-white font-semibold">{c.name}</p>
                                                                                                                                                                                                                                                                                                                                                                                                                                            <p className="text-gray-500 text-xs">{c.symbol}</p>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  </td>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  <td className="px-4 py-3 text-white font-bold">${c.current_price >= 1 ? c.current_price.toLocaleString() : c.current_price.toFixed(4)}</td>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  <td className="px-4 py-3"><Pct v={c.price_change_24h_pct} /></td>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  <td className="px-4 py-3"><Pct v={c.price_change_7d} /></td>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  <td className="px-4 py-3 text-white">{fmt(c.market_cap)}</td>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  <td className="px-4 py-3 text-gray-300">{fmt(c.total_volume)}</td>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  <td className="px-4 py-3 text-gray-400">{c.circulating_supply}</td>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                </tr>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            ))}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      </tbody>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              </table>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          );
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          EOF
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          import { useState } from 'react';
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          import Navbar from './components/Navbar';
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          import Dashboard from './components/Dashboard';
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          import Markets from './pages/Markets';
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          import Workbench from './pages/Workbench';
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          import Events from './pages/Events';
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          import Transcripts from './pages/Transcripts';
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          export default function App() {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            const [page, setPage] = useState('dashboard');
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              const pages = {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  dashboard: <Dashboard />,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      markets:   <Markets />,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          workbench: <Workbench />,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              events:    <Events />,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  transcripts: <Transcripts />,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    };
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      return (
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          <div className="flex flex-col h-screen bg-[#060d1a] text-gray-100 overflow-hidden">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                <Navbar activePage={page} onNavigate={setPage} />
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      <main className="flex-1 overflow-auto">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              {pages[page] || <Dashboard />}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    </main>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          );
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          EOF
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          /** @type {import('tailwindcss').Config} */
export default {
  content: ['./index.html','./src/**/*.{js,jsx}'],
  theme: { extend: {} },
  plugins: [],
};
